nexus-bin: bump to 2.15.2-03

diff --git a/dev-java/nexus-bin/files/nexus.init b/dev-java/nexus-bin/files/nexus.init
--- a/dev-java/nexus-bin/files/nexus.init
+++ b/dev-java/nexus-bin/files/nexus.init
@@ -11,7 +11,7 @@ APP_LONG_NAME="Sonatype Nexus Repository Manager"
 WRAPPER_CMD=`find /usr/share/nexus/bin/jsw -name wrapper`
 WRAPPER_CONF="/etc/nexus/wrapper.conf"
 
-# Priority at which to run the wrapper.  See "man nice" for valid priorities.
+# Priority at which to run the wrapper. See "man nice" for valid priorities.
 #  nice is only used if a priority is specified.
 PRIORITY=
 
@@ -28,7 +28,7 @@ TMPDIR="/var/tmp/nexus"
 
 # If specified, the Wrapper will be run as the specified user.
 # IMPORTANT - Make sure that the user has the required privileges to write
-#  the PID file and wrapper.log files.  Failure to be able to write the log
+#  the PID file and wrapper.log files.	Failure to be able to write the log
 #  file will cause the Wrapper to exit without any way to write out an error
 #  message.
 # NOTE - This will set the user which is used to run the Wrapper as well as
@@ -46,48 +46,48 @@ RUN_AS_USER=nexus
 
 # Get the fully qualified path to the script
 case $0 in
-    /*)
-        SCRIPT="$0"
-        ;;
-    *)
-        PWD=`pwd`
-        SCRIPT="$PWD/$0"
-        ;;
+	/*)
+		SCRIPT="$0"
+		;;
+	*)
+		PWD=`pwd`
+		SCRIPT="$PWD/$0"
+		;;
 esac
 
 # Resolve the true real path without any sym links.
 CHANGED=true
 while [ "X$CHANGED" != "X" ]
 do
-    # Change spaces to ":" so the tokens can be parsed.
-    SAFESCRIPT=`echo $SCRIPT | sed -e 's; ;:;g'`
-    # Get the real path to this script, resolving any symbolic links
-    TOKENS=`echo $SAFESCRIPT | sed -e 's;/; ;g'`
-    REALPATH=
-    for C in $TOKENS; do
-        # Change any ":" in the token back to a space.
-        C=`echo $C | sed -e 's;:; ;g'`
-        REALPATH="$REALPATH/$C"
-        # If REALPATH is a sym link, resolve it.  Loop for nested links.
-        while [ -h "$REALPATH" ] ; do
-            LS="`ls -ld "$REALPATH"`"
-            LINK="`expr "$LS" : '.*-> \(.*\)$'`"
-            if expr "$LINK" : '/.*' > /dev/null; then
-                # LINK is absolute.
-                REALPATH="$LINK"
-            else
-                # LINK is relative.
-                REALPATH="`dirname "$REALPATH"`""/$LINK"
-            fi
-        done
-    done
+	# Change spaces to ":" so the tokens can be parsed.
+	SAFESCRIPT=`echo $SCRIPT | sed -e 's; ;:;g'`
+	# Get the real path to this script, resolving any symbolic links
+	TOKENS=`echo $SAFESCRIPT | sed -e 's;/; ;g'`
+	REALPATH=
+	for C in $TOKENS; do
+		# Change any ":" in the token back to a space.
+		C=`echo $C | sed -e 's;:; ;g'`
+		REALPATH="$REALPATH/$C"
+		# If REALPATH is a sym link, resolve it.  Loop for nested links.
+		while [ -h "$REALPATH" ] ; do
+			LS="`ls -ld "$REALPATH"`"
+			LINK="`expr "$LS" : '.*-> \(.*\)$'`"
+			if expr "$LINK" : '/.*' > /dev/null; then
+				# LINK is absolute.
+				REALPATH="$LINK"
+			else
+				# LINK is relative.
+				REALPATH="`dirname "$REALPATH"`""/$LINK"
+			fi
+		done
+	done
 
-    if [ "$REALPATH" = "$SCRIPT" ]
-    then
-        CHANGED=""
-    else
-        SCRIPT="$REALPATH"
-    fi
+	if [ "$REALPATH" = "$SCRIPT" ]
+	then
+		CHANGED=""
+	else
+		SCRIPT="$REALPATH"
+	fi
 done
 
 # Change the current directory to the location of the script
@@ -99,19 +99,19 @@ REALDIR=`pwd`
 FIRST_CHAR=`echo $PIDDIR | cut -c1,1`
 if [ "$FIRST_CHAR" != "/" ]
 then
-    PIDDIR=$REALDIR/$PIDDIR
+	PIDDIR=$REALDIR/$PIDDIR
 fi
 # Same test for WRAPPER_CMD
 FIRST_CHAR=`echo $WRAPPER_CMD | cut -c1,1`
 if [ "$FIRST_CHAR" != "/" ]
 then
-    WRAPPER_CMD=$REALDIR/$WRAPPER_CMD
+	WRAPPER_CMD=$REALDIR/$WRAPPER_CMD
 fi
 # Same test for WRAPPER_CONF
 FIRST_CHAR=`echo $WRAPPER_CONF | cut -c1,1`
 if [ "$FIRST_CHAR" != "/" ]
 then
-    WRAPPER_CONF=$REALDIR/$WRAPPER_CONF
+	WRAPPER_CONF=$REALDIR/$WRAPPER_CONF
 fi
 
 # Process ID
@@ -125,132 +125,132 @@ pid=""
 PSEXE="/usr/bin/ps"
 if [ ! -x "$PSEXE" ]
 then
-    PSEXE="/bin/ps"
-    if [ ! -x "$PSEXE" ]
-    then
-        echo "Unable to locate 'ps'."
-        echo "Please report this message along with the location of the command on your system."
-        exit 1
-    fi
+	PSEXE="/bin/ps"
+	if [ ! -x "$PSEXE" ]
+	then
+		echo "Unable to locate 'ps'."
+		echo "Please report this message along with the location of the command on your system."
+		exit 1
+	fi
 fi
 
 # Resolve the os
 DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
 case "$DIST_OS" in
-    'sunos')
-        DIST_OS="solaris"
-        ;;
-    'hp-ux' | 'hp-ux64')
-        DIST_OS="hpux"
-        ;;
-    'darwin')
-        DIST_OS="macosx"
-        ;;
-    'unix_sv')
-        DIST_OS="unixware"
-        ;;
+	'sunos')
+		DIST_OS="solaris"
+		;;
+	'hp-ux' | 'hp-ux64')
+		DIST_OS="hpux"
+		;;
+	'darwin')
+		DIST_OS="macosx"
+		;;
+	'unix_sv')
+		DIST_OS="unixware"
+		;;
 esac
 
 # Resolve the architecture
 DIST_ARCH=`uname -p | tr [:upper:] [:lower:] | tr -d [:blank:]`
 if [ "$DIST_ARCH" = "unknown" ]
 then
-    DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
+	DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
 fi
 case "$DIST_ARCH" in
-    'amd64' | 'athlon' | 'ia32' | 'ia64' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
-        DIST_ARCH="x86"
-        ;;
-    'ip27')
-        DIST_ARCH="mips"
-        ;;
-    'power' | 'powerpc' | 'power_pc' | 'ppc64')
-        DIST_ARCH="ppc"
-        ;;
-    'pa_risc' | 'pa-risc')
-        DIST_ARCH="parisc"
-        ;;
-    'sun4u' | 'sparcv9')
-        DIST_ARCH="sparc"
-        ;;
-    '9000/800')
-        DIST_ARCH="parisc"
-        ;;
+	'amd64' | 'athlon' | 'ia32' | 'ia64' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
+		DIST_ARCH="x86"
+		;;
+	'ip27')
+		DIST_ARCH="mips"
+		;;
+	'power' | 'powerpc' | 'power_pc' | 'ppc64')
+		DIST_ARCH="ppc"
+		;;
+	'pa_risc' | 'pa-risc')
+		DIST_ARCH="parisc"
+		;;
+	'sun4u' | 'sparcv9')
+		DIST_ARCH="sparc"
+		;;
+	'9000/800')
+		DIST_ARCH="parisc"
+		;;
 esac
 
 outputFile() {
-    if [ -f "$1" ]
-    then
-        echo "  $1 (Found but not executable.)";
-    else
-        echo "  $1"
-    fi
+	if [ -f "$1" ]
+	then
+		echo "	$1 (Found but not executable.)";
+	else
+		echo "	$1"
+	fi
 }
 
 # Decide on the wrapper binary to use.
 # If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
 #  platforms, if the 64-bit binary exists then the distribution most
-#  likely wants to use long names.  Otherwise, look for the default.
+#  likely wants to use long names.	Otherwise, look for the default.
 # For macosx, we also want to look for universal binaries.
 WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
 if [ -x "$WRAPPER_TEST_CMD" ]
 then
-    WRAPPER_CMD="$WRAPPER_TEST_CMD"
+	WRAPPER_CMD="$WRAPPER_TEST_CMD"
 else
-    if [ "$DIST_OS" = "macosx" ]
-    then
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-            if [ -x "$WRAPPER_TEST_CMD" ]
-            then
-                WRAPPER_CMD="$WRAPPER_TEST_CMD"
-            else
-                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-                if [ -x "$WRAPPER_TEST_CMD" ]
-                then
-                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-                else
-                    if [ ! -x "$WRAPPER_CMD" ]
-                    then
-                        echo "Unable to locate any of the following binaries:"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
-                        outputFile "$WRAPPER_CMD"
-                        exit 1
-                    fi
-                fi
-            fi
-        fi
-    else
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            if [ ! -x "$WRAPPER_CMD" ]
-            then
-                echo "Unable to locate any of the following binaries:"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                outputFile "$WRAPPER_CMD"
-                exit 1
-            fi
-        fi
-    fi
+	if [ "$DIST_OS" = "macosx" ]
+	then
+		WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
+		if [ -x "$WRAPPER_TEST_CMD" ]
+		then
+			WRAPPER_CMD="$WRAPPER_TEST_CMD"
+		else
+			WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+			if [ -x "$WRAPPER_TEST_CMD" ]
+			then
+				WRAPPER_CMD="$WRAPPER_TEST_CMD"
+			else
+				WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
+				if [ -x "$WRAPPER_TEST_CMD" ]
+				then
+					WRAPPER_CMD="$WRAPPER_TEST_CMD"
+				else
+					if [ ! -x "$WRAPPER_CMD" ]
+					then
+						echo "Unable to locate any of the following binaries:"
+						outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+						outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
+						outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+						outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
+						outputFile "$WRAPPER_CMD"
+						exit 1
+					fi
+				fi
+			fi
+		fi
+	else
+		WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+		if [ -x "$WRAPPER_TEST_CMD" ]
+		then
+			WRAPPER_CMD="$WRAPPER_TEST_CMD"
+		else
+			if [ ! -x "$WRAPPER_CMD" ]
+			then
+				echo "Unable to locate any of the following binaries:"
+				outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
+				outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
+				outputFile "$WRAPPER_CMD"
+				exit 1
+			fi
+		fi
+	fi
 fi
 
 # Build the nice clause
 if [ "X$PRIORITY" = "X" ]
 then
-    CMDNICE=""
+	CMDNICE=""
 else
-    CMDNICE="nice -$PRIORITY"
+	CMDNICE="nice -$PRIORITY"
 fi
 
 # Build the anchor file clause.
@@ -267,131 +267,131 @@ fi
 LOCKPROP=
 if [ -d $LOCKDIR ]
 then
-    if [ -w $LOCKDIR ]
-    then
-        LOCKPROP=wrapper.lockfile=\"$LOCKFILE\"
-    fi
+	if [ -w $LOCKDIR ]
+	then
+		LOCKPROP=wrapper.lockfile=\"$LOCKFILE\"
+	fi
 fi
 
 getpid() {
-    if [ -f "$PIDFILE" ]
-    then
-        if [ -r "$PIDFILE" ]
-        then
-            pid=`cat "$PIDFILE"`
-            if [ "X$pid" != "X" ]
-            then
-                # It is possible that 'a' process with the pid exists but that it is not the
-                #  correct process.  This can happen in a number of cases, but the most
-                #  common is during system startup after an unclean shutdown.
-                # The ps statement below looks for the specific wrapper command running as
-                #  the pid.  If it is not found then the pid file is considered to be stale.
-                pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
-                if [ "X$pidtest" = "X" ]
-                then
-                    # This is a stale pid file.
-                    rm -f "$PIDFILE"
-                    echo "Removed stale pid file: $PIDFILE"
-                    pid=""
-                fi
-            fi
-        else
-            echo "Cannot read $PIDFILE."
-            exit 1
-        fi
-    fi
+	if [ -f "$PIDFILE" ]
+	then
+		if [ -r "$PIDFILE" ]
+		then
+			pid=`cat "$PIDFILE"`
+			if [ "X$pid" != "X" ]
+			then
+				# It is possible that 'a' process with the pid exists but that it is not the
+				#  correct process.	 This can happen in a number of cases, but the most
+				#  common is during system startup after an unclean shutdown.
+				# The ps statement below looks for the specific wrapper command running as
+				#  the pid.	 If it is not found then the pid file is considered to be stale.
+				pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
+				if [ "X$pidtest" = "X" ]
+				then
+					# This is a stale pid file.
+					rm -f "$PIDFILE"
+					echo "Removed stale pid file: $PIDFILE"
+					pid=""
+				fi
+			fi
+		else
+			echo "Cannot read $PIDFILE."
+			exit 1
+		fi
+	fi
 }
 
 testpid() {
-    pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
-    if [ "X$pid" = "X" ]
-    then
-        # Process is gone so remove the pid file.
-        rm -f "$PIDFILE"
-        pid=""
-    fi
+	pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+	if [ "X$pid" = "X" ]
+	then
+		# Process is gone so remove the pid file.
+		rm -f "$PIDFILE"
+		pid=""
+	fi
 }
 
 depend() {
-    need net
-    use dns logger
+	need net
+	use dns logger
 }
 
 checkconfig() {
 	checkpath -q -d -o ${RUN_AS_USER}:nexus ${PIDDIR}
-    checkpath -q -d -o ${RUN_AS_USER}:nexus ${TMPDIR}
-    return 0
+	checkpath -q -d -o ${RUN_AS_USER}:nexus ${TMPDIR}
+	return 0
 }
 
 start() {
-    checkconfig || return 1
-    ebegin "Starting $APP_LONG_NAME"
+	checkconfig || return 1
+	ebegin "Starting $APP_LONG_NAME"
 
-    getpid
-    if [ "X$pid" = "X" ]
-    then
-        # The string passed to eval must handles spaces in paths correctly.
-        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $LOCKPROP"
-        su -p "${RUN_AS_USER}" -c "${COMMAND_LINE}"
+	getpid
+	if [ "X$pid" = "X" ]
+	then
+		# The string passed to eval must handles spaces in paths correctly.
+		COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $LOCKPROP"
+		su -p "${RUN_AS_USER}" -c "${COMMAND_LINE}"
 	fi
-    eend $?
+	eend $?
 }
 
 stop() {
-    ebegin "Stopping $APP_LONG_NAME"
+	ebegin "Stopping $APP_LONG_NAME"
 
-    getpid
-    if [ "X$pid" != "X" ]
-    then
-        if [ "X$IGNORE_SIGNALS" = "X" ]
-        then
-            # Running so try to stop it.
-            kill $pid
-            if [ $? -ne 0 ]
-            then
-                # An explanation for the failure should have been given
-                eend 1
-            fi
-        else
-            rm -f "$ANCHORFILE"
-            if [ -f "$ANCHORFILE" ]
-            then
-                # An explanation for the failure should have been given
-                eend 1
-            fi
-        fi
+	getpid
+	if [ "X$pid" != "X" ]
+	then
+		if [ "X$IGNORE_SIGNALS" = "X" ]
+		then
+			# Running so try to stop it.
+			kill $pid
+			if [ $? -ne 0 ]
+			then
+				# An explanation for the failure should have been given
+				eend 1
+			fi
+		else
+			rm -f "$ANCHORFILE"
+			if [ -f "$ANCHORFILE" ]
+			then
+				# An explanation for the failure should have been given
+				eend 1
+			fi
+		fi
 
-        # We can not predict how long it will take for the wrapper to
-        #  actually stop as it depends on settings in wrapper.conf.
-        #  Loop until it does.
-        savepid=$pid
-        CNT=0
-        TOTCNT=0
-        while [ "X$pid" != "X" ]
-        do
-            # Show a waiting message every 5 seconds.
-            if [ "$CNT" -lt "5" ]
-            then
-                CNT=`expr $CNT + 1`
-            else
-                echo "Waiting for $APP_LONG_NAME to exit..."
-                CNT=0
-            fi
-            TOTCNT=`expr $TOTCNT + 1`
+		# We can not predict how long it will take for the wrapper to
+		#  actually stop as it depends on settings in wrapper.conf.
+		#  Loop until it does.
+		savepid=$pid
+		CNT=0
+		TOTCNT=0
+		while [ "X$pid" != "X" ]
+		do
+			# Show a waiting message every 5 seconds.
+			if [ "$CNT" -lt "5" ]
+			then
+				CNT=`expr $CNT + 1`
+			else
+				echo "Waiting for $APP_LONG_NAME to exit..."
+				CNT=0
+			fi
+			TOTCNT=`expr $TOTCNT + 1`
 
-            sleep 1
+			sleep 1
 
-            testpid
-        done
+			testpid
+		done
 
-        pid=$savepid
-        testpid
-        if [ "X$pid" != "X" ]
-        then
-            eend 1
-        fi
-    fi
+		pid=$savepid
+		testpid
+		if [ "X$pid" != "X" ]
+		then
+			eend 1
+		fi
+	fi
 
-    eend $?
+	eend $?
 }
 
